/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

//! Cross-Crate Kernel Example
//!
//! This example tests the ability to use kernels defined in a library crate.
//!
//! ## Structure
//!
//! ```text
//! cross_crate_kernel/
//! ├── Cargo.toml          # Binary crate (this file)
//! ├── src/main.rs         # Uses kernels from kernel-lib
//! └── kernel-lib/         # Library crate
//!     ├── Cargo.toml
//!     └── src/lib.rs      # Defines #[kernel] functions
//! ```
//!
//! ## What This Tests
//!
//! 1. Generic kernels defined in external crate (`kernel_lib::scale<T>`)
//! 2. Monomorphization at use site (`scale::<f32>` instantiated here)
//! 3. PTX generation for cross-crate kernels
//! 4. Const-generic entries instantiated for two values in the consuming crate
//! 5. Generic and ordinary non-inlined device helpers from external crates
//!
//! ## Build and Run
//!
//! ```bash
//! cargo oxide run cross_crate_kernel
//! ```

use cuda_core::{CudaContext, DeviceBuffer, LaunchConfig};
use cuda_device::{DisjointSlice, cuda_module, kernel, thread};

// Import the public kernel functions and their generated `<kernel>_ptx_name`
// helpers. Entry symbols and marker types remain implementation details.
use kernel_lib::kernels;

#[cuda_module]
mod plain_helper_kernels {
    use super::*;

    /// Local entry calling an ordinary non-generic dependency function.
    #[kernel]
    pub fn transform_with_plain_helper(input: &[u32], mut output: DisjointSlice<u32>) {
        let idx = thread::index_1d();
        let idx_raw = idx.get();
        if let Some(out_elem) = output.get_mut(idx) {
            *out_elem = kernel_lib::kernels::plain_device_helper(input[idx_raw]);
        }
    }
}

fn specialization_names() -> [&'static str; 4] {
    [
        kernels::scale_ptx_name::<f32>(),
        kernels::scale_ptx_name::<i32>(),
        kernels::add_const_ptx_name::<4>(),
        kernels::add_const_ptx_name::<8>(),
    ]
}

fn verify_generated_ptx() {
    let ptx = std::fs::read_to_string(concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/cross_crate_kernel.ptx"
    ))
    .expect("read cross_crate_kernel.ptx; run `cargo oxide build cross_crate_kernel` first");

    for name in specialization_names() {
        let entry = format!(".visible .entry {name}(");
        assert!(
            ptx.contains(&entry),
            "missing cross-crate PTX entry `{name}`"
        );
    }
}

fn main() {
    println!("=== Cross-Crate Kernel Test ===\n");
    println!("Testing kernels defined in kernel-lib crate.\n");

    if std::env::args().any(|arg| arg == "--print-specializations") {
        for name in specialization_names() {
            println!("{name}");
        }
        return;
    }
    if std::env::args().any(|arg| arg == "--verify-ptx") {
        verify_generated_ptx();
        println!("cross-crate host lookup names match all four PTX entries");
        return;
    }

    verify_generated_ptx();

    // Initialize CUDA
    let ctx = CudaContext::new(0).expect("Failed to create CUDA context");
    let stream = ctx.default_stream();

    // Load PTX (generated by rustc-codegen-cuda)
    // The PTX contains all monomorphized kernels from both crates
    let module = ctx
        .load_module_from_file("cross_crate_kernel.ptx")
        .expect("Failed to load PTX module");
    let module = kernels::from_module(module).expect("Failed to initialize typed CUDA module");
    let plain_helper_module =
        plain_helper_kernels::load(&ctx).expect("load plain helper regression module");

    // Test data
    const N: usize = 1024;

    // =========================================================================
    // Test 1: Generic scale kernel from library (f32)
    // =========================================================================
    println!("Test 1: kernel_lib::scale::<f32>");
    {
        let factor: f32 = 2.5;
        let input: Vec<f32> = (0..N).map(|i| i as f32).collect();

        let input_dev = DeviceBuffer::from_host(&stream, &input).unwrap();
        let mut output_dev = DeviceBuffer::<f32>::zeroed(&stream, N).unwrap();

        // SAFETY: launch shape/resources match the kernel; buffers cover its accesses.
        unsafe {
            module.scale::<f32>(
                (stream).as_ref(),
                LaunchConfig::for_num_elems(N as u32),
                factor,
                &input_dev,
                &mut output_dev,
            )
        }
        .expect("Kernel launch failed");

        let output: Vec<f32> = output_dev.to_host_vec(&stream).unwrap();

        let errors = (0..N)
            .filter(|&i| (output[i] - input[i] * factor).abs() > 1e-5)
            .count();

        if errors == 0 {
            println!("  ✓ PASSED: scale::<f32> from library works!\n");
        } else {
            println!("  ✗ FAILED: {} errors\n", errors);
            std::process::exit(1);
        }
    }

    // =========================================================================
    // Test 2: Generic scale kernel from library (i32)
    // =========================================================================
    println!("Test 2: kernel_lib::scale::<i32>");
    {
        let factor: i32 = 3;
        let input: Vec<i32> = (0..N as i32).collect();

        let input_dev = DeviceBuffer::from_host(&stream, &input).unwrap();
        let mut output_dev = DeviceBuffer::<i32>::zeroed(&stream, N).unwrap();

        // SAFETY: launch shape/resources match the kernel; buffers cover its accesses.
        unsafe {
            module.scale::<i32>(
                (stream).as_ref(),
                LaunchConfig::for_num_elems(N as u32),
                factor,
                &input_dev,
                &mut output_dev,
            )
        }
        .expect("Kernel launch failed");

        let output: Vec<i32> = output_dev.to_host_vec(&stream).unwrap();

        let errors = (0..N).filter(|&i| output[i] != input[i] * factor).count();

        if errors == 0 {
            println!("  ✓ PASSED: scale::<i32> from library works!\n");
        } else {
            println!("  ✗ FAILED: {} errors\n", errors);
            std::process::exit(1);
        }
    }

    // =========================================================================
    // Test 3: Generic add kernel from library
    // =========================================================================
    println!("Test 3: kernel_lib::add::<f32>");
    {
        let a: Vec<f32> = (0..N).map(|i| i as f32).collect();
        let b: Vec<f32> = (0..N).map(|i| (i * 2) as f32).collect();

        let a_dev = DeviceBuffer::from_host(&stream, &a).unwrap();
        let b_dev = DeviceBuffer::from_host(&stream, &b).unwrap();
        let mut c_dev = DeviceBuffer::<f32>::zeroed(&stream, N).unwrap();

        // SAFETY: launch shape/resources match the kernel; buffers cover its accesses.
        unsafe {
            module.add::<f32>(
                (stream).as_ref(),
                LaunchConfig::for_num_elems(N as u32),
                &a_dev,
                &b_dev,
                &mut c_dev,
            )
        }
        .expect("Kernel launch failed");

        let c: Vec<f32> = c_dev.to_host_vec(&stream).unwrap();

        let errors = (0..N)
            .filter(|&i| (c[i] - (a[i] + b[i])).abs() > 1e-5)
            .count();

        if errors == 0 {
            println!("  ✓ PASSED: add::<f32> from library works!\n");
        } else {
            println!("  ✗ FAILED: {} errors\n", errors);
            std::process::exit(1);
        }
    }

    // =========================================================================
    // Test 4: Kernel that uses device helper function from library
    // =========================================================================
    println!("Test 4: kernel_lib::scale_with_helper::<f32> (uses device helper)");
    {
        let factor: f32 = 4.0;
        let input: Vec<f32> = (0..N).map(|i| i as f32).collect();

        let input_dev = DeviceBuffer::from_host(&stream, &input).unwrap();
        let mut output_dev = DeviceBuffer::<f32>::zeroed(&stream, N).unwrap();

        // SAFETY: launch shape/resources match the kernel; buffers cover its accesses.
        unsafe {
            module.scale_with_helper::<f32>(
                (stream).as_ref(),
                LaunchConfig::for_num_elems(N as u32),
                factor,
                &input_dev,
                &mut output_dev,
            )
        }
        .expect("Kernel launch failed");

        let output: Vec<f32> = output_dev.to_host_vec(&stream).unwrap();

        let errors = (0..N)
            .filter(|&i| (output[i] - input[i] * factor).abs() > 1e-5)
            .count();

        if errors == 0 {
            println!("  ✓ PASSED: scale_with_helper uses device function from library!\n");
        } else {
            println!("  ✗ FAILED: {} errors\n", errors);
            std::process::exit(1);
        }
    }

    // =========================================================================
    // Test 5: Const-generic entries from the library
    // =========================================================================
    println!("Test 5: kernel_lib::add_const::<4/8>");
    {
        let input: Vec<u32> = (0..N as u32).collect();
        let input_dev = DeviceBuffer::from_host(&stream, &input).unwrap();
        let mut output_4 = DeviceBuffer::<u32>::zeroed(&stream, N).unwrap();
        let mut output_8 = DeviceBuffer::<u32>::zeroed(&stream, N).unwrap();
        let config = LaunchConfig::for_num_elems(N as u32);

        // SAFETY: launch shape/resources match the kernel; buffers cover its accesses.
        unsafe { module.add_const::<4>((stream).as_ref(), config, &input_dev, &mut output_4) }
            .expect("add_const::<4> launch failed");
        // SAFETY: launch shape/resources match the kernel; buffers cover its accesses.
        unsafe { module.add_const::<8>((stream).as_ref(), config, &input_dev, &mut output_8) }
            .expect("add_const::<8> launch failed");

        let result_4 = output_4.to_host_vec(&stream).unwrap();
        let result_8 = output_8.to_host_vec(&stream).unwrap();
        assert!((0..N).all(|i| result_4[i] == input[i] + 4));
        assert!((0..N).all(|i| result_8[i] == input[i] + 8));
        println!("  ✓ PASSED: const-generic library entries remain distinct!\n");
    }

    // =========================================================================
    // Test 6: Ordinary non-generic, non-inlined dependency MIR
    // =========================================================================
    println!("Test 6: dependency helper imported without relying on inlining");
    {
        let input: Vec<u32> = (0..N as u32).collect();
        let input_dev = DeviceBuffer::from_host(&stream, &input).unwrap();
        let mut output_dev = DeviceBuffer::<u32>::zeroed(&stream, N).unwrap();

        // SAFETY: launch shape/resources match the kernel; buffers cover its accesses.
        unsafe {
            plain_helper_module.transform_with_plain_helper(
                &stream,
                LaunchConfig::for_num_elems(N as u32),
                &input_dev,
                &mut output_dev,
            )
        }
        .expect("transform_with_plain_helper launch failed");

        let output = output_dev.to_host_vec(&stream).unwrap();
        assert!((0..N).all(|i| output[i] == input[i].wrapping_mul(3).wrapping_add(7)));
        println!("  ✓ PASSED: plain dependency MIR was collected and executed!\n");
    }

    println!("=== All Cross-Crate Tests Passed! ===");
    println!("\nThis demonstrates:");
    println!("  - Generic kernels can be defined in library crates");
    println!("  - They are monomorphized when used in the application");
    println!("  - PTX is generated for all used instantiations");
    println!("  - Const values participate in cross-crate kernel identity");
    println!("  - Generic and non-inlined device helpers from libraries also work");
}
