/*
 * SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */

//! Regression for optimized PTX-to-cubin materialization.
//!
//! Run:
//!   cargo oxide run materialized_fixed_vector_loops \
//!     --materialize-cubin --arch sm_86

use cuda_core::{CudaContext, DeviceBuffer, LaunchConfig};
use cuda_device::{DisjointSlice, cuda_module, kernel, thread};

const COMPONENTS: usize = 3;
const NODES: usize = 2;
const VECTOR_VALUES: usize = COMPONENTS * NODES;
const INPUT_VALUES: usize = VECTOR_VALUES * 2;

#[derive(Clone, Copy)]
struct FixedVector([[f32; COMPONENTS]; NODES]);

impl FixedVector {
    #[inline(always)]
    unsafe fn load(input: &[f32], base: usize) -> Self {
        let mut values = [[0.0; COMPONENTS]; NODES];
        for node in 0..NODES {
            for component in 0..COMPONENTS {
                // SAFETY: the kernel contract requires INPUT_VALUES values for
                // every launched output element.
                values[node][component] =
                    unsafe { *input.get_unchecked(base + node * COMPONENTS + component) };
            }
        }
        Self(values)
    }

    #[inline(always)]
    fn saxpy(self, rhs: Self, alpha: f32, beta: f32) -> Self {
        let mut values = [[0.0; COMPONENTS]; NODES];
        for node in 0..NODES {
            for component in 0..COMPONENTS {
                values[node][component] =
                    alpha * self.0[node][component] + beta * rhs.0[node][component];
            }
        }
        Self(values)
    }

    #[inline(always)]
    fn dot(self, rhs: Self) -> f32 {
        let mut sum = 0.0;
        for node in 0..NODES {
            for component in 0..COMPONENTS {
                sum += self.0[node][component] * rhs.0[node][component];
            }
        }
        sum
    }
}

#[cuda_module]
mod kernels {
    use super::*;

    /// Load two fixed vectors, form `alpha * x + beta * y`, then return its
    /// dot product with `x`.
    ///
    /// # Safety
    ///
    /// `input` must contain `INPUT_VALUES` values for every output element.
    #[kernel]
    pub unsafe fn fixed_vector_loops(
        input: &[f32],
        alpha: f32,
        beta: f32,
        mut output: DisjointSlice<f32>,
    ) {
        let tid = thread::index_1d();
        let raw_tid = tid.get();
        if let Some(output) = output.get_mut(tid) {
            let base = raw_tid * INPUT_VALUES;
            // SAFETY: upheld by the kernel contract above.
            let x = unsafe { FixedVector::load(input, base) };
            // SAFETY: upheld by the kernel contract above.
            let y = unsafe { FixedVector::load(input, base + VECTOR_VALUES) };
            *output = x.saxpy(y, alpha, beta).dot(x);
        }
    }
}

fn host_result(input: &[f32], element: usize, alpha: f32, beta: f32) -> f32 {
    let base = element * INPUT_VALUES;
    let mut sum = 0.0;
    for node in 0..NODES {
        for component in 0..COMPONENTS {
            let offset = node * COMPONENTS + component;
            let x = input[base + offset];
            let y = input[base + VECTOR_VALUES + offset];
            sum += (alpha * x + beta * y) * x;
        }
    }
    sum
}

fn assert_optimized_ptx() {
    let path = concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/materialized_fixed_vector_loops.ptx"
    );
    let ptx = std::fs::read_to_string(path).expect("materialized PTX sidecar was not emitted");
    assert!(
        ptx.contains("Generated by LLVM NVPTX Back-End"),
        "materialized cubin did not retain the optimized LLVM PTX route"
    );
    assert!(
        !ptx.contains("Generated by NVIDIA NVVM Compiler"),
        "materialization unexpectedly forced deferred NVVM IR compilation"
    );
    for forbidden in [".local", "ld.local", "st.local", "trap;"] {
        assert!(
            !ptx.contains(forbidden),
            "optimized PTX unexpectedly contains {forbidden:?}"
        );
    }
}

fn main() {
    const ELEMENTS: usize = 257;
    const ALPHA: f32 = 1.25;
    const BETA: f32 = -0.375;

    let input = (0..ELEMENTS * INPUT_VALUES)
        .map(|index| (index as f32 - 300.0) * 0.00390625)
        .collect::<Vec<_>>();
    let expected = (0..ELEMENTS)
        .map(|element| host_result(&input, element, ALPHA, BETA))
        .collect::<Vec<_>>();

    let context = CudaContext::new(0).expect("failed to create CUDA context");
    let stream = context.default_stream();
    let input_device = DeviceBuffer::from_host(&stream, &input).expect("failed to upload input");
    let mut output_device =
        DeviceBuffer::<f32>::zeroed(&stream, ELEMENTS).expect("failed to allocate output");

    let module = kernels::load(&context).expect("failed to load materialized CUDA module");
    // SAFETY: the input has INPUT_VALUES values per launched output element.
    unsafe {
        module.fixed_vector_loops(
            &stream,
            LaunchConfig::for_num_elems(ELEMENTS as u32),
            &input_device,
            ALPHA,
            BETA,
            &mut output_device,
        )
    }
    .expect("fixed-vector kernel launch failed");

    let actual = output_device
        .to_host_vec(&stream)
        .expect("failed to download output");
    for (index, (actual, expected)) in actual.iter().zip(&expected).enumerate() {
        let tolerance = 2.0e-5 * expected.abs().max(1.0);
        assert!(
            (actual - expected).abs() <= tolerance,
            "element {index}: expected {expected}, got {actual}"
        );
    }

    assert_optimized_ptx();
    println!("materialized fixed vector loops: PASS");
}
